### PR TITLE
Add colour scheme override for privacy.resistFingerprinting

### PR DESCRIPTION
**Pull request by kierandrewett**
I created a separate configuration option called `privacy.resistFingerprinting.ignoreColorScheme` which forces the colour scheme to be `light` in pages which can stop fingerprinting. However, it essentially kills off dark mode on sites. So I have added a option to override that behavior back to the default of forcing the colour scheme to be light.

https://github.com/dothq/browser-desktop/blob/48e0671811b35bfae3c9e3079a8850aa06024bad/patches/modules-libpref-init-StaticPrefList-yaml.patch#L32-L38

https://github.com/dothq/browser-desktop/blob/48e0671811b35bfae3c9e3079a8850aa06024bad/patches/dom-base-Document-cpp.patch#L3-L15

### CODE REVIEW

**Review by trickypr — APPROVED** [review]

**Comment by kierandrewett** [comment]
@trickypr Was this tested before you reviewed changes?

**Comment by trickypr** [comment]
No, I just did code review. Do you want me to build and test it?

**Comment by kierandrewett** [comment]
Yes

**Review by trickypr — CHANGES_REQUESTED** [review]
`./melon download` doesn't initialize the `src` folder correctly and breaks everything.

**Pull request merged**
