### PR TITLE
Create a template based on snippetman

### PR DESCRIPTION
**Pull request by trickypr**
This is a template that is loosely based on the code for Snippetman. There are some things that should be noted:
- [ ] I have no idea how your new build system works, so this doesn't integrate with it at all or bind to any specific `gecko-dev` version
- [ ] I can only guarantee that this will work on linux. It might work on macos. It definitely won't work on Windows
- [ ] There are a bunch of custom patches. I think that newer versions of `gecko-dev` they might be dead, so you might need to manually apply and export them

image

### CODE REVIEW

**Comment by kierandrewett** [comment]
Does this have xulStore at all?

**Comment by trickypr** [comment]
It looks like it is in `/toolkit`, so it should, however I have only used the sqlite module for persistence.

**Comment by kierandrewett** [comment]
And the usual components work like browserelement and jarfiles?

**Comment by trickypr** [comment]
Jar files work fine, but there is some jank that needs to be handled (which is mentioned in the readme) to get react hotreloading working. Browser elements **should** work, but I am not sure how react will handle them and they have no typescript types yet

**Comment by kierandrewett** [comment]
How could we get this functional on Windows?

**Comment by trickypr** [comment]
You would need to copy over the windows packaging code from `browser/` or 	`comm-centeral/mail`

**Comment by kierandrewett** [comment]
Ah yes, okay I'm currently out right now but I will give this a look over ASAP.

**Comment by kierandrewett** [comment]
Few things that need changing but I am happy to merge as I can easily fix these myself.

**Pull request merged**
